package com.my.ttms.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class Play implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_id
     *
     * @mbggenerated
     */
    private Integer playId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_type_id
     *
     * @mbggenerated
     */
    private Integer playTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_lang_id
     *
     * @mbggenerated
     */
    private Integer playLangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_name
     *
     * @mbggenerated
     */
    private String playName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_introduction
     *
     * @mbggenerated
     */
    private String playIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_image
     *
     * @mbggenerated
     */
    private String playImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_length
     *
     * @mbggenerated
     */
    private Integer playLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_ticket_price
     *
     * @mbggenerated
     */
    private BigDecimal playTicketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_status
     *
     * @mbggenerated
     */
    private Short playStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column play.play_type
     *
     * @mbggenerated
     */
    private String playType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table play
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_id
     *
     * @return the value of play.play_id
     *
     * @mbggenerated
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_id
     *
     * @param playId the value for play.play_id
     *
     * @mbggenerated
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_type_id
     *
     * @return the value of play.play_type_id
     *
     * @mbggenerated
     */
    public Integer getPlayTypeId() {
        return playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_type_id
     *
     * @param playTypeId the value for play.play_type_id
     *
     * @mbggenerated
     */
    public void setPlayTypeId(Integer playTypeId) {
        this.playTypeId = playTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_lang_id
     *
     * @return the value of play.play_lang_id
     *
     * @mbggenerated
     */
    public Integer getPlayLangId() {
        return playLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_lang_id
     *
     * @param playLangId the value for play.play_lang_id
     *
     * @mbggenerated
     */
    public void setPlayLangId(Integer playLangId) {
        this.playLangId = playLangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_name
     *
     * @return the value of play.play_name
     *
     * @mbggenerated
     */
    public String getPlayName() {
        return playName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_name
     *
     * @param playName the value for play.play_name
     *
     * @mbggenerated
     */
    public void setPlayName(String playName) {
        this.playName = playName == null ? null : playName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_introduction
     *
     * @return the value of play.play_introduction
     *
     * @mbggenerated
     */
    public String getPlayIntroduction() {
        return playIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_introduction
     *
     * @param playIntroduction the value for play.play_introduction
     *
     * @mbggenerated
     */
    public void setPlayIntroduction(String playIntroduction) {
        this.playIntroduction = playIntroduction == null ? null : playIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_image
     *
     * @return the value of play.play_image
     *
     * @mbggenerated
     */
    public String getPlayImage() {
        return playImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_image
     *
     * @param playImage the value for play.play_image
     *
     * @mbggenerated
     */
    public void setPlayImage(String playImage) {
        this.playImage = playImage == null ? null : playImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_length
     *
     * @return the value of play.play_length
     *
     * @mbggenerated
     */
    public Integer getPlayLength() {
        return playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_length
     *
     * @param playLength the value for play.play_length
     *
     * @mbggenerated
     */
    public void setPlayLength(Integer playLength) {
        this.playLength = playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_ticket_price
     *
     * @return the value of play.play_ticket_price
     *
     * @mbggenerated
     */
    public BigDecimal getPlayTicketPrice() {
        return playTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_ticket_price
     *
     * @param playTicketPrice the value for play.play_ticket_price
     *
     * @mbggenerated
     */
    public void setPlayTicketPrice(BigDecimal playTicketPrice) {
        this.playTicketPrice = playTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_status
     *
     * @return the value of play.play_status
     *
     * @mbggenerated
     */
    public Short getPlayStatus() {
        return playStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_status
     *
     * @param playStatus the value for play.play_status
     *
     * @mbggenerated
     */
    public void setPlayStatus(Short playStatus) {
        this.playStatus = playStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column play.play_type
     *
     * @return the value of play.play_type
     *
     * @mbggenerated
     */
    public String getPlayType() {
        return playType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column play.play_type
     *
     * @param playType the value for play.play_type
     *
     * @mbggenerated
     */
    public void setPlayType(String playType) {
        this.playType = playType == null ? null : playType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", playId=").append(playId);
        sb.append(", playTypeId=").append(playTypeId);
        sb.append(", playLangId=").append(playLangId);
        sb.append(", playName=").append(playName);
        sb.append(", playIntroduction=").append(playIntroduction);
        sb.append(", playImage=").append(playImage);
        sb.append(", playLength=").append(playLength);
        sb.append(", playTicketPrice=").append(playTicketPrice);
        sb.append(", playStatus=").append(playStatus);
        sb.append(", playType=").append(playType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}