package com.my.ttms.bean;

import java.io.Serializable;

public class Playdetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playdetail.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playdetail.mainactor
     *
     * @mbggenerated
     */
    private String mainactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playdetail.playintro
     *
     * @mbggenerated
     */
    private String playintro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playdetail.play_id
     *
     * @mbggenerated
     */
    private Integer playId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playdetail.director
     *
     * @return the value of playdetail.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playdetail.director
     *
     * @param director the value for playdetail.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playdetail.mainactor
     *
     * @return the value of playdetail.mainactor
     *
     * @mbggenerated
     */
    public String getMainactor() {
        return mainactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playdetail.mainactor
     *
     * @param mainactor the value for playdetail.mainactor
     *
     * @mbggenerated
     */
    public void setMainactor(String mainactor) {
        this.mainactor = mainactor == null ? null : mainactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playdetail.playintro
     *
     * @return the value of playdetail.playintro
     *
     * @mbggenerated
     */
    public String getPlayintro() {
        return playintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playdetail.playintro
     *
     * @param playintro the value for playdetail.playintro
     *
     * @mbggenerated
     */
    public void setPlayintro(String playintro) {
        this.playintro = playintro == null ? null : playintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playdetail.play_id
     *
     * @return the value of playdetail.play_id
     *
     * @mbggenerated
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playdetail.play_id
     *
     * @param playId the value for playdetail.play_id
     *
     * @mbggenerated
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", director=").append(director);
        sb.append(", mainactor=").append(mainactor);
        sb.append(", playintro=").append(playintro);
        sb.append(", playId=").append(playId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}