package com.my.ttms.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class SaleItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_item_id
     *
     * @mbggenerated
     */
    private Long saleItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.ticket_id
     *
     * @mbggenerated
     */
    private Long ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_ID
     *
     * @mbggenerated
     */
    private Long saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_item.sale_item_price
     *
     * @mbggenerated
     */
    private BigDecimal saleItemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_item_id
     *
     * @return the value of sale_item.sale_item_id
     *
     * @mbggenerated
     */
    public Long getSaleItemId() {
        return saleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_item_id
     *
     * @param saleItemId the value for sale_item.sale_item_id
     *
     * @mbggenerated
     */
    public void setSaleItemId(Long saleItemId) {
        this.saleItemId = saleItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.ticket_id
     *
     * @return the value of sale_item.ticket_id
     *
     * @mbggenerated
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.ticket_id
     *
     * @param ticketId the value for sale_item.ticket_id
     *
     * @mbggenerated
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_ID
     *
     * @return the value of sale_item.sale_ID
     *
     * @mbggenerated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_ID
     *
     * @param saleId the value for sale_item.sale_ID
     *
     * @mbggenerated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_item.sale_item_price
     *
     * @return the value of sale_item.sale_item_price
     *
     * @mbggenerated
     */
    public BigDecimal getSaleItemPrice() {
        return saleItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_item.sale_item_price
     *
     * @param saleItemPrice the value for sale_item.sale_item_price
     *
     * @mbggenerated
     */
    public void setSaleItemPrice(BigDecimal saleItemPrice) {
        this.saleItemPrice = saleItemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", saleItemId=").append(saleItemId);
        sb.append(", ticketId=").append(ticketId);
        sb.append(", saleId=").append(saleId);
        sb.append(", saleItemPrice=").append(saleItemPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}