package com.my.ttms.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Sale implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_ID
     *
     * @mbggenerated
     */
    private Long saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.emp_id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_time
     *
     * @mbggenerated
     */
    private Date saleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_payment
     *
     * @mbggenerated
     */
    private BigDecimal salePayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_change
     *
     * @mbggenerated
     */
    private BigDecimal saleChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_type
     *
     * @mbggenerated
     */
    private Short saleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_status
     *
     * @mbggenerated
     */
    private Short saleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_ID
     *
     * @return the value of sale.sale_ID
     *
     * @mbggenerated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_ID
     *
     * @param saleId the value for sale.sale_ID
     *
     * @mbggenerated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.emp_id
     *
     * @return the value of sale.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.emp_id
     *
     * @param empId the value for sale.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_time
     *
     * @return the value of sale.sale_time
     *
     * @mbggenerated
     */
    public Date getSaleTime() {
        return saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_time
     *
     * @param saleTime the value for sale.sale_time
     *
     * @mbggenerated
     */
    public void setSaleTime(Date saleTime) {
        this.saleTime = saleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_payment
     *
     * @return the value of sale.sale_payment
     *
     * @mbggenerated
     */
    public BigDecimal getSalePayment() {
        return salePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_payment
     *
     * @param salePayment the value for sale.sale_payment
     *
     * @mbggenerated
     */
    public void setSalePayment(BigDecimal salePayment) {
        this.salePayment = salePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_change
     *
     * @return the value of sale.sale_change
     *
     * @mbggenerated
     */
    public BigDecimal getSaleChange() {
        return saleChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_change
     *
     * @param saleChange the value for sale.sale_change
     *
     * @mbggenerated
     */
    public void setSaleChange(BigDecimal saleChange) {
        this.saleChange = saleChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_type
     *
     * @return the value of sale.sale_type
     *
     * @mbggenerated
     */
    public Short getSaleType() {
        return saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_type
     *
     * @param saleType the value for sale.sale_type
     *
     * @mbggenerated
     */
    public void setSaleType(Short saleType) {
        this.saleType = saleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_status
     *
     * @return the value of sale.sale_status
     *
     * @mbggenerated
     */
    public Short getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_status
     *
     * @param saleStatus the value for sale.sale_status
     *
     * @mbggenerated
     */
    public void setSaleStatus(Short saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", saleId=").append(saleId);
        sb.append(", empId=").append(empId);
        sb.append(", saleTime=").append(saleTime);
        sb.append(", salePayment=").append(salePayment);
        sb.append(", saleChange=").append(saleChange);
        sb.append(", saleType=").append(saleType);
        sb.append(", saleStatus=").append(saleStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}