package com.my.ttms.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Schedule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_id
     *
     * @mbggenerated
     */
    private Integer scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_name
     *
     * @mbggenerated
     */
    private String scheduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.studio_id
     *
     * @mbggenerated
     */
    private Integer studioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.play_id
     *
     * @mbggenerated
     */
    private Integer playId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.schedule_time
     *
     * @mbggenerated
     */
    private Date scheduleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.isticket
     *
     * @mbggenerated
     */
    private Integer isticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_id
     *
     * @return the value of schedule.schedule_id
     *
     * @mbggenerated
     */
    public Integer getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_id
     *
     * @param scheduleId the value for schedule.schedule_id
     *
     * @mbggenerated
     */
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_name
     *
     * @return the value of schedule.schedule_name
     *
     * @mbggenerated
     */
    public String getScheduleName() {
        return scheduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_name
     *
     * @param scheduleName the value for schedule.schedule_name
     *
     * @mbggenerated
     */
    public void setScheduleName(String scheduleName) {
        this.scheduleName = scheduleName == null ? null : scheduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.studio_id
     *
     * @return the value of schedule.studio_id
     *
     * @mbggenerated
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.studio_id
     *
     * @param studioId the value for schedule.studio_id
     *
     * @mbggenerated
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.play_id
     *
     * @return the value of schedule.play_id
     *
     * @mbggenerated
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.play_id
     *
     * @param playId the value for schedule.play_id
     *
     * @mbggenerated
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.schedule_time
     *
     * @return the value of schedule.schedule_time
     *
     * @mbggenerated
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.schedule_time
     *
     * @param scheduleTime the value for schedule.schedule_time
     *
     * @mbggenerated
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.discount
     *
     * @return the value of schedule.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.discount
     *
     * @param discount the value for schedule.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.price
     *
     * @return the value of schedule.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.price
     *
     * @param price the value for schedule.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.status
     *
     * @return the value of schedule.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.status
     *
     * @param status the value for schedule.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.isticket
     *
     * @return the value of schedule.isticket
     *
     * @mbggenerated
     */
    public Integer getIsticket() {
        return isticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.isticket
     *
     * @param isticket the value for schedule.isticket
     *
     * @mbggenerated
     */
    public void setIsticket(Integer isticket) {
        this.isticket = isticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.end_time
     *
     * @return the value of schedule.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.end_time
     *
     * @param endTime the value for schedule.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scheduleId=").append(scheduleId);
        sb.append(", scheduleName=").append(scheduleName);
        sb.append(", studioId=").append(studioId);
        sb.append(", playId=").append(playId);
        sb.append(", scheduleTime=").append(scheduleTime);
        sb.append(", discount=").append(discount);
        sb.append(", price=").append(price);
        sb.append(", status=").append(status);
        sb.append(", isticket=").append(isticket);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}