package com.my.ttms.bean;

import java.io.Serializable;

public class Seat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_id
     *
     * @mbggenerated
     */
    private Integer seatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.studio_id
     *
     * @mbggenerated
     */
    private Integer studioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_row
     *
     * @mbggenerated
     */
    private Integer seatRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_column
     *
     * @mbggenerated
     */
    private Integer seatColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.seat_status
     *
     * @mbggenerated
     */
    private Integer seatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seat
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_id
     *
     * @return the value of seat.seat_id
     *
     * @mbggenerated
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_id
     *
     * @param seatId the value for seat.seat_id
     *
     * @mbggenerated
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.studio_id
     *
     * @return the value of seat.studio_id
     *
     * @mbggenerated
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.studio_id
     *
     * @param studioId the value for seat.studio_id
     *
     * @mbggenerated
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_row
     *
     * @return the value of seat.seat_row
     *
     * @mbggenerated
     */
    public Integer getSeatRow() {
        return seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_row
     *
     * @param seatRow the value for seat.seat_row
     *
     * @mbggenerated
     */
    public void setSeatRow(Integer seatRow) {
        this.seatRow = seatRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_column
     *
     * @return the value of seat.seat_column
     *
     * @mbggenerated
     */
    public Integer getSeatColumn() {
        return seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_column
     *
     * @param seatColumn the value for seat.seat_column
     *
     * @mbggenerated
     */
    public void setSeatColumn(Integer seatColumn) {
        this.seatColumn = seatColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.seat_status
     *
     * @return the value of seat.seat_status
     *
     * @mbggenerated
     */
    public Integer getSeatStatus() {
        return seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.seat_status
     *
     * @param seatStatus the value for seat.seat_status
     *
     * @mbggenerated
     */
    public void setSeatStatus(Integer seatStatus) {
        this.seatStatus = seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seat
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seatId=").append(seatId);
        sb.append(", studioId=").append(studioId);
        sb.append(", seatRow=").append(seatRow);
        sb.append(", seatColumn=").append(seatColumn);
        sb.append(", seatStatus=").append(seatStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}