package com.my.ttms.bean;

import java.io.Serializable;

public class Studio implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_id
     *
     * @mbggenerated
     */
    private Integer studioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_name
     *
     * @mbggenerated
     */
    private String studioName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_row_count
     *
     * @mbggenerated
     */
    private Integer studioRowCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_col_count
     *
     * @mbggenerated
     */
    private Integer studioColCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studio.studio_introduction
     *
     * @mbggenerated
     */
    private String studioIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studio
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_id
     *
     * @return the value of studio.studio_id
     *
     * @mbggenerated
     */
    public Integer getStudioId() {
        return studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_id
     *
     * @param studioId the value for studio.studio_id
     *
     * @mbggenerated
     */
    public void setStudioId(Integer studioId) {
        this.studioId = studioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_name
     *
     * @return the value of studio.studio_name
     *
     * @mbggenerated
     */
    public String getStudioName() {
        return studioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_name
     *
     * @param studioName the value for studio.studio_name
     *
     * @mbggenerated
     */
    public void setStudioName(String studioName) {
        this.studioName = studioName == null ? null : studioName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_row_count
     *
     * @return the value of studio.studio_row_count
     *
     * @mbggenerated
     */
    public Integer getStudioRowCount() {
        return studioRowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_row_count
     *
     * @param studioRowCount the value for studio.studio_row_count
     *
     * @mbggenerated
     */
    public void setStudioRowCount(Integer studioRowCount) {
        this.studioRowCount = studioRowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_col_count
     *
     * @return the value of studio.studio_col_count
     *
     * @mbggenerated
     */
    public Integer getStudioColCount() {
        return studioColCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_col_count
     *
     * @param studioColCount the value for studio.studio_col_count
     *
     * @mbggenerated
     */
    public void setStudioColCount(Integer studioColCount) {
        this.studioColCount = studioColCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studio.studio_introduction
     *
     * @return the value of studio.studio_introduction
     *
     * @mbggenerated
     */
    public String getStudioIntroduction() {
        return studioIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studio.studio_introduction
     *
     * @param studioIntroduction the value for studio.studio_introduction
     *
     * @mbggenerated
     */
    public void setStudioIntroduction(String studioIntroduction) {
        this.studioIntroduction = studioIntroduction == null ? null : studioIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studio
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studioId=").append(studioId);
        sb.append(", studioName=").append(studioName);
        sb.append(", studioRowCount=").append(studioRowCount);
        sb.append(", studioColCount=").append(studioColCount);
        sb.append(", studioIntroduction=").append(studioIntroduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}