package com.my.ttms.bean;

import java.io.Serializable;

public class Userdetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_telNum
     *
     * @mbggenerated
     */
    private String userTelnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_bankcarid
     *
     * @mbggenerated
     */
    private String userBankcarid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_paypwd
     *
     * @mbggenerated
     */
    private String userPaypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_sex
     *
     * @mbggenerated
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_age
     *
     * @mbggenerated
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userdetail.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_telNum
     *
     * @return the value of userdetail.user_telNum
     *
     * @mbggenerated
     */
    public String getUserTelnum() {
        return userTelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_telNum
     *
     * @param userTelnum the value for userdetail.user_telNum
     *
     * @mbggenerated
     */
    public void setUserTelnum(String userTelnum) {
        this.userTelnum = userTelnum == null ? null : userTelnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_address
     *
     * @return the value of userdetail.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_address
     *
     * @param userAddress the value for userdetail.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_bankcarid
     *
     * @return the value of userdetail.user_bankcarid
     *
     * @mbggenerated
     */
    public String getUserBankcarid() {
        return userBankcarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_bankcarid
     *
     * @param userBankcarid the value for userdetail.user_bankcarid
     *
     * @mbggenerated
     */
    public void setUserBankcarid(String userBankcarid) {
        this.userBankcarid = userBankcarid == null ? null : userBankcarid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_paypwd
     *
     * @return the value of userdetail.user_paypwd
     *
     * @mbggenerated
     */
    public String getUserPaypwd() {
        return userPaypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_paypwd
     *
     * @param userPaypwd the value for userdetail.user_paypwd
     *
     * @mbggenerated
     */
    public void setUserPaypwd(String userPaypwd) {
        this.userPaypwd = userPaypwd == null ? null : userPaypwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_sex
     *
     * @return the value of userdetail.user_sex
     *
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_sex
     *
     * @param userSex the value for userdetail.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_age
     *
     * @return the value of userdetail.user_age
     *
     * @mbggenerated
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_age
     *
     * @param userAge the value for userdetail.user_age
     *
     * @mbggenerated
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userdetail.user_id
     *
     * @return the value of userdetail.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userdetail.user_id
     *
     * @param userId the value for userdetail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userTelnum=").append(userTelnum);
        sb.append(", userAddress=").append(userAddress);
        sb.append(", userBankcarid=").append(userBankcarid);
        sb.append(", userPaypwd=").append(userPaypwd);
        sb.append(", userSex=").append(userSex);
        sb.append(", userAge=").append(userAge);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}