package com.my.ttms.bean;

import java.util.ArrayList;
import java.util.List;

public class UserdetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public UserdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserTelnumIsNull() {
            addCriterion("user_telNum is null");
            return (Criteria) this;
        }

        public Criteria andUserTelnumIsNotNull() {
            addCriterion("user_telNum is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelnumEqualTo(String value) {
            addCriterion("user_telNum =", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumNotEqualTo(String value) {
            addCriterion("user_telNum <>", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumGreaterThan(String value) {
            addCriterion("user_telNum >", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumGreaterThanOrEqualTo(String value) {
            addCriterion("user_telNum >=", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumLessThan(String value) {
            addCriterion("user_telNum <", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumLessThanOrEqualTo(String value) {
            addCriterion("user_telNum <=", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumLike(String value) {
            addCriterion("user_telNum like", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumNotLike(String value) {
            addCriterion("user_telNum not like", value, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumIn(List<String> values) {
            addCriterion("user_telNum in", values, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumNotIn(List<String> values) {
            addCriterion("user_telNum not in", values, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumBetween(String value1, String value2) {
            addCriterion("user_telNum between", value1, value2, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserTelnumNotBetween(String value1, String value2) {
            addCriterion("user_telNum not between", value1, value2, "userTelnum");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("user_address is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("user_address is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("user_address =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("user_address <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("user_address >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("user_address >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("user_address <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("user_address <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("user_address like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("user_address not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("user_address in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("user_address not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("user_address between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("user_address not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridIsNull() {
            addCriterion("user_bankcarid is null");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridIsNotNull() {
            addCriterion("user_bankcarid is not null");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridEqualTo(String value) {
            addCriterion("user_bankcarid =", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridNotEqualTo(String value) {
            addCriterion("user_bankcarid <>", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridGreaterThan(String value) {
            addCriterion("user_bankcarid >", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridGreaterThanOrEqualTo(String value) {
            addCriterion("user_bankcarid >=", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridLessThan(String value) {
            addCriterion("user_bankcarid <", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridLessThanOrEqualTo(String value) {
            addCriterion("user_bankcarid <=", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridLike(String value) {
            addCriterion("user_bankcarid like", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridNotLike(String value) {
            addCriterion("user_bankcarid not like", value, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridIn(List<String> values) {
            addCriterion("user_bankcarid in", values, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridNotIn(List<String> values) {
            addCriterion("user_bankcarid not in", values, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridBetween(String value1, String value2) {
            addCriterion("user_bankcarid between", value1, value2, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserBankcaridNotBetween(String value1, String value2) {
            addCriterion("user_bankcarid not between", value1, value2, "userBankcarid");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdIsNull() {
            addCriterion("user_paypwd is null");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdIsNotNull() {
            addCriterion("user_paypwd is not null");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdEqualTo(String value) {
            addCriterion("user_paypwd =", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdNotEqualTo(String value) {
            addCriterion("user_paypwd <>", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdGreaterThan(String value) {
            addCriterion("user_paypwd >", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_paypwd >=", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdLessThan(String value) {
            addCriterion("user_paypwd <", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdLessThanOrEqualTo(String value) {
            addCriterion("user_paypwd <=", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdLike(String value) {
            addCriterion("user_paypwd like", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdNotLike(String value) {
            addCriterion("user_paypwd not like", value, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdIn(List<String> values) {
            addCriterion("user_paypwd in", values, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdNotIn(List<String> values) {
            addCriterion("user_paypwd not in", values, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdBetween(String value1, String value2) {
            addCriterion("user_paypwd between", value1, value2, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserPaypwdNotBetween(String value1, String value2) {
            addCriterion("user_paypwd not between", value1, value2, "userPaypwd");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNull() {
            addCriterion("user_sex is null");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNotNull() {
            addCriterion("user_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUserSexEqualTo(String value) {
            addCriterion("user_sex =", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotEqualTo(String value) {
            addCriterion("user_sex <>", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThan(String value) {
            addCriterion("user_sex >", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThanOrEqualTo(String value) {
            addCriterion("user_sex >=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThan(String value) {
            addCriterion("user_sex <", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThanOrEqualTo(String value) {
            addCriterion("user_sex <=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLike(String value) {
            addCriterion("user_sex like", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotLike(String value) {
            addCriterion("user_sex not like", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexIn(List<String> values) {
            addCriterion("user_sex in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotIn(List<String> values) {
            addCriterion("user_sex not in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexBetween(String value1, String value2) {
            addCriterion("user_sex between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotBetween(String value1, String value2) {
            addCriterion("user_sex not between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserAgeIsNull() {
            addCriterion("user_age is null");
            return (Criteria) this;
        }

        public Criteria andUserAgeIsNotNull() {
            addCriterion("user_age is not null");
            return (Criteria) this;
        }

        public Criteria andUserAgeEqualTo(Integer value) {
            addCriterion("user_age =", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeNotEqualTo(Integer value) {
            addCriterion("user_age <>", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeGreaterThan(Integer value) {
            addCriterion("user_age >", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_age >=", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeLessThan(Integer value) {
            addCriterion("user_age <", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeLessThanOrEqualTo(Integer value) {
            addCriterion("user_age <=", value, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeIn(List<Integer> values) {
            addCriterion("user_age in", values, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeNotIn(List<Integer> values) {
            addCriterion("user_age not in", values, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeBetween(Integer value1, Integer value2) {
            addCriterion("user_age between", value1, value2, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("user_age not between", value1, value2, "userAge");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userdetail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}