package com.my.ttms.dao;

import com.my.ttms.bean.Play;
import com.my.ttms.bean.Playdetail;
import com.my.ttms.bean.PlaydetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlaydetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int countByExample(PlaydetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int deleteByExample(PlaydetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int insert(Playdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int insertSelective(Playdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    List<Playdetail> selectByExample(PlaydetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Playdetail record, @Param("example") PlaydetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Playdetail record, @Param("example") PlaydetailExample example);

    List<Playdetail>  selectAll();
}