package com.my.ttms.dao;

import com.my.ttms.bean.Play;
import com.my.ttms.bean.PlayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int countByExample(PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int deleteByExample(PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int insert(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int insertSelective(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    List<Play> selectByExample(PlayExample example);

    List<Play> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    Play selectByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Play record, @Param("example") PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Play record, @Param("example") PlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Play record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table play
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Play record);

}