package com.my.ttms.dao;

import com.my.ttms.bean.SaleItem;
import com.my.ttms.bean.SaleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int countByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int deleteByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long saleItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int insert(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int insertSelective(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    List<SaleItem> selectByExample(SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    SaleItem selectByPrimaryKey(Long saleItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SaleItem record, @Param("example") SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SaleItem record, @Param("example") SaleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SaleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaleItem record);
}