package com.my.ttms.dao;

import com.my.ttms.bean.Userdetail;
import com.my.ttms.bean.UserdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int countByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int deleteByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int insert(Userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int insertSelective(Userdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    List<Userdetail> selectByExample(UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Userdetail record, @Param("example") UserdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Userdetail record, @Param("example") UserdetailExample example);
}